name: pig-latin
version: 1.2.0.7

dependencies:
  - base

library:
  exposed-modules: PigLatin
  source-dirs: src
  ghc-options: -Wall
  dependencies:
    - containers

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - pig-latin
      - hspec
