(("Donald" salary 520)
 ("Jeff" salary 590)
 ("Lisa" salary 560)
 ("Betty" salary 580)
 ("Donald" address "Delaware")
 ("Jeff" address "Florida")
 ("Lisa" address "Georgia")
 ("Betty" address "Hawaii"))
