name: house
version: 0.1.0.3

dependencies:
  - base

library:
  exposed-modules: House
  source-dirs: src
  ghc-options: -Wall
  dependencies:
    - mtl

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - house
      - hspec
