name: hamming
version: 2.3.0.10

dependencies:
  - base

library:
  exposed-modules: Hamming
  source-dirs: src
  ghc-options: -Wall
  dependencies:
    - ghc

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - hamming
      - hspec
