name: scripting
version: 0.1.0.0
github: Javran/Thinking-dumps
license: BSD3
author: Javran Cheng
maintainer: javran.c@gmail.com
copyright: "Copyright: (c) 2021 Javran Cheng"

description: description

dependencies:
- base
- turtle
- system-filepath
- text
- containers
- foldl
- process
- SafeSemaphore

library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -O2
    - -fno-warn-unused-imports
    - -fno-warn-unused-top-binds

executables:
  demo:
    main: Main.hs
    source-dirs: exe
    dependencies:
      - scripting
    ghc-options:
      - -Wall
      - -O2
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

tests:
  hspec:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - scripting
      - QuickCheck
      - hspec
    ghc-options:
      - -Wall
      - -O2
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is Spec
