name: lts-updater
version: 0.1.0.0
github: Javran/lts-updater
license: BSD3
author: Javran Cheng
maintainer: javran.c@gmail.com
copyright: "Copyright: (c) 2021 Javran Cheng"

description: description

dependencies:
- base
- turtle
- system-filepath
- text
- containers
- foldl

library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -O2

executables:
  demo:
    main: Main.hs
    source-dirs: exe
    dependencies:
      - lts-updater
    ghc-options:
      - -Wall
      - -O2
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

tests:
  hspec:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - lts-updater
      - QuickCheck
      - hspec
    ghc-options:
      - -Wall
      - -O2
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is Spec
