name: sgf-parsing
version: 1.2.0.5

dependencies:
  - base
  - containers
  - text

library:
  exposed-modules: Sgf
  source-dirs: src
  ghc-options: -Wall
  dependencies:
    - parsec

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - sgf-parsing
      - hspec
