name: nucleotide-count
version: 1.3.0.8

dependencies:
  - base
  - containers

library:
  exposed-modules: DNA
  source-dirs: src
  ghc-options: -Wall
  dependencies:
    - mtl

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - nucleotide-count
      - hspec
