name: kindergarten-garden
version: 1.1.1.8

dependencies:
  - base

library:
  exposed-modules: Garden
  source-dirs: src
  ghc-options: -Wall
  dependencies:
    - split
    - containers

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - kindergarten-garden
      - hspec
