name: palindrome-products
version: 1.1.0.4

dependencies:
  - base

library:
  exposed-modules: Palindromes
  source-dirs: src
  ghc-options: -Wall
  dependencies:
    - containers

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - palindrome-products
      - hspec
