name: grade-school
version: 1.0.0.4

dependencies:
  - base

library:
  exposed-modules: School
  source-dirs: src
  ghc-options: -Wall
  dependencies:
    - containers

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - grade-school
      - hspec
