name: dominoes
version: 2.1.0.9

dependencies:
  - base

library:
  exposed-modules: Dominoes
  source-dirs: src
  ghc-options: -Wall

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - dominoes
      - hspec
