name: bowling
version: 1.2.0.7

dependencies:
  - base

library:
  exposed-modules: Bowling
  source-dirs: src
  ghc-options: -Wall
  dependencies:
    - mtl

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - bowling
      - hspec
