name: word-count
version: 1.4.0.8

dependencies:
  - base

library:
  exposed-modules: WordCount
  source-dirs: src
  ghc-options: -Wall
  dependencies:
    - containers

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - word-count
      - hspec
