name: all-your-base
version: 2.3.0.8

dependencies:
  - base

library:
  exposed-modules: Base
  source-dirs: src
  ghc-options: -Wall
  dependencies:
    - mtl

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - all-your-base
      - hspec
