- ignore: {name: Avoid lambda using `infix`}
- ignore: {name: Use uncurry}
- ignore: {name: Use camelCase}
- ignore: {name: Use newtype instead of data}
- ignore: {name: Use String}
- ignore: {name: Use bimap}
- ignore: {name: Redundant ==}
