resolver: lts-16.4
packages:
- .
extra-deps:
- Euterpea-2.0.7
- HSoM-1.0.0
- HCodecs-0.5.2
- PortMidi-0.2.0.0
- UISF-0.4.0.0
- arrows-0.4.4.2
- bytestring-0.10.8.2
- pure-fft-0.2.0
- Stream-0.4.7.2
- text-1.2.4.0
- binary-0.8.8.0
- lazysmallcheck-0.6

allow-newer: true
