name: change
version: 1.3.0.7

dependencies:
  - base

library:
  exposed-modules: Change
  source-dirs: src
  ghc-options: -Wall
  dependencies:
    - MemoTrie
    - extra

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - change
      - hspec
