name: scrabble-score
version: 1.1.0.5

dependencies:
  - base
  - array

library:
  exposed-modules: Scrabble
  source-dirs: src
  ghc-options: -Wall

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - scrabble-score
      - hspec
