name: rail-fence-cipher
version: 1.1.0.4

dependencies:
  - base

library:
  exposed-modules: RailFenceCipher
  source-dirs: src
  ghc-options: -Wall
  dependencies:
    - vector
    - dlist

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - rail-fence-cipher
      - hspec
