name: perfect-numbers
version: 1.1.0.4

dependencies:
  - base

library:
  exposed-modules: PerfectNumbers
  source-dirs: src
  ghc-options: -Wall

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - perfect-numbers
      - hspec
