name: alphametics
version: 1.3.0.6

dependencies:
  - base

library:
  exposed-modules: Alphametics
  source-dirs: src
  ghc-options: -Wall
  dependencies:
    - containers

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - alphametics
      - hspec
