name: robot-simulator
version: 3.2.0.8

dependencies:
  - base

library:
  exposed-modules: Robot
  source-dirs: src
  ghc-options: -Wall
  dependencies:
    - lens
    - mtl

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - robot-simulator
      - hspec
