(load "../common/utils.scm")
(load "../common/test-utils.scm")

(define (half-adder a b s c)
  (let ((d (make-wire))
        (e (make-wire)))
    (or-gate a b d)
    (and-gate a b c)
    (inverter c e)
    (and-gate d e s)
  'ok))

(define (full-adder a b c-in sum c-out)
  (let ((s  (make-wire))
        (c1 (make-wire))
        (c2 (make-wire)))
    (half-adder b c-in s c1)
    (half-adder a s sum c2)
    (or-gate c1 c2 c-out)
    'ok))

(define (ripple-carry-adder as bs ss c)
  (define (ripple-carry-adder-intern as bs c0 ss c1)
    (if (= (length as) 1)
      (begin
        (assert (= (length bs) 1))
        (assert (= (length ss) 1))
        (full-adder (car as) (car bs) c0 (car ss) c1))
      (let ((c-mid (make-wire)))
        (ripple-carry-adder-intern (cdr as) (cdr bs) c0 (cdr ss) c-mid)
        (full-adder (car as) (car bs) c-mid (car ss) c1))))
  (let ((c0 (make-wire)))
    (set-signal! c0 0)
    (ripple-carry-adder-intern as bs c0 ss c)
    'ok))

(end-script)
