name: spiral-matrix
version: 1.1.0.3

dependencies:
  - base

library:
  exposed-modules: Spiral
  source-dirs: src
  ghc-options: -Wall

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - spiral-matrix
      - hspec
